<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
//                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
//            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('home')?>">Code Tiburon</a>
                </div>
<!--                <div class="navbar-collapse collapse">-->
<!--                    <ul class="nav navbar-nav navbar-right">-->
<!--                        <li><a href="http://getbootstrap.com/examples/dashboard/#">Dashboard</a></li>-->
<!--                        <li><a href="http://getbootstrap.com/examples/dashboard/#">Settings</a></li>-->
<!--                        <li><a href="http://getbootstrap.com/examples/dashboard/#">Profile</a></li>-->
<!--                        <li><a href="http://getbootstrap.com/examples/dashboard/#">Help</a></li>-->
<!--                    </ul>-->
<!--                    <form class="navbar-form navbar-right">-->
<!--                        <input type="text" class="form-control" placeholder="Search...">-->
<!--                    </form>-->
<!--                </div>-->
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <?=$this->partial('partials/navigation.phtml', array('navigation' => $navigation))?>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <?=$this->content?>
                </div>
            </div>
            <?=$this->inlineScript()?>
    </body>
</html>